name: publish
on:
  workflow_dispatch:
  push:
    tags: [ v* ]

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release ${{ github.ref_name }}
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
          name: ${{ github.ref_name }}
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: false

      - name: Release Latest
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: latest
          generateReleaseNotes: true
          name: latest
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true

      - name: Release ${{ matrix.goos }}-${{ matrix.goarch }} ${{ github.ref_name }}
        uses: wangyoucao577/go-release-action@v1.48
        with:
          overwrite: true
          binary_name: render
          asset_name: ${{ matrix.goos }}-${{ matrix.goarch }}-render
          release_tag: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: "-extldflags=-static"
      - name: Release ${{ matrix.goos }}-${{ matrix.goarch }} to latest
        uses: wangyoucao577/go-release-action@v1.48
        with:
          overwrite: true
          binary_name: render
          asset_name: ${{ matrix.goos }}-${{ matrix.goarch }}-render
          release_tag: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: "-extldflags=-static"